sudo: required
services: 
  - docker

before_install:
  - docker build -t dockerdemobyzzn/docker-react -f Dockerfile.dev .

script:
  - docker run dockerdemobyzzn/docker-react npm run test -- -- coverage