sudo: required
services: 
  - docker

before_install:
  - docker build -t dockerdemobyzzn/docker-react -f Dockerfile.dev .

script:
  - docker run dockerdemobyzzn/docker-react npm run test -- -- coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "arn:aws:s3:::elasticbeanstalk-ap-southeast-1-163765774124"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

  